# Generated by Django 4.0.6 on 2022-07-07 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameinfo', '0002_genre_name_loc'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='developer',
            field=models.CharField(default='default', max_length=255),
            preserve_default=False,
        ),
    ]
