# Generated by Django 4.0.6 on 2022-07-08 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameinfo', '0003_game_developer'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='slug',
            field=models.SlugField(db_index=False, default='default', max_length=255),
            preserve_default=False,
        ),
    ]
