# Generated by Django 4.0.6 on 2022-07-11 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gameinfo', '0005_alter_game_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_create', models.DateTimeField(auto_now_add=True)),
                ('text', models.TextField()),
                ('game', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='gameinfo.game')),
            ],
        ),
    ]
